### ISSUE TITLE
加锁失败消息重新投递

### ISSUE THREAD

**Issue by Jarvan12th** [weihubeats/wh-mq-Idempotent#8]
如果加锁失败则返回消费失败让MQ重新投递，这是在哪里实现的呢？

src/main/java/com/mq/idempotent/core/aop/MqIdempotentAnnotationInterceptor.java
`if (!lock(key)) {
            log.info("有消息正在消费");
            throw new Exception("有消息正在消费");
        }`
这里没有重新投递的处理，是在AOP内部做的嘛？

**Comment by weihubeats** [comment]
这个还没有实现,当时有规划,然后忘了,后续可以实现

**Comment by weihubeats** [comment]
突然忘了，这里加锁失败就直接返回异常。让MQ以为消费失败重新投递消息，不需要我们实现

**Comment by weihubeats** [comment]
所以是不需要我们额外处理的
